import type { Metadata } from 'next'
import './globals.css'
import { TanstackQueryClientProvider } from '@/components/providers/query-client'
import { JotaiProvider } from '@/components/providers/jotai'
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="zh-Hans-CN">
			<body className="antialiased py-8 px-4  sm:px-8 md:px-16">
				<TanstackQueryClientProvider>
					<JotaiProvider>{children}</JotaiProvider>
				</TanstackQueryClientProvider>
			</body>
		</html>
	)
}
