import type { Metadata } from 'next'
import './globals.css'
import { TanstackQueryClientProvider } from '@/components/providers/query-client'
import { JotaiProvider } from '@/components/providers/jotai'
import { SiteHeader } from './_components/site-header'
import { IsClientProvider } from '@/components/providers/is-client'
import { Toaster } from '@/components/ui/sonner'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="zh-Hans-CN">
			<body className="antialiased">
				<SiteHeader />
				<TanstackQueryClientProvider>
					<JotaiProvider>
						<IsClientProvider>
							<main className="py-8 px-4 sm:px-8 md:px-16">{children}</main>
						</IsClientProvider>
					</JotaiProvider>
				</TanstackQueryClientProvider>
				<Toaster />
			</body>
		</html>
	)
}
